const express=require('express')
const router=express.Router()
const articlesController=require('../controllers/articles.controller')
const articlesMiddleware=require('../middlewares/articles.middleware')
const tokenMiddleware=require('../middlewares/token.middleware')
const allowTo=require('../middlewares/role.middleware')
const uploadImageMiddleware=require('../middlewares/uploadImage.middleware')
router.route('/')
        .get(articlesController.getArticles)
        .post(tokenMiddleware,allowTo('admin'),uploadImageMiddleware,articlesMiddleware.middlewareBody,articlesController.createArticle)
router.route('/latest10')
        .get(articlesController.getLatestArticles)
router.route('/all_articles')
        .get(articlesController.getAllArticles)
router.route('/all_drafts')
        .get(articlesController.getAllDrafts)  
router.route('/tags')
        .get(articlesController.getAllTags)

router.route('/image')
        .post(tokenMiddleware,allowTo('admin'),uploadImageMiddleware,articlesController.uploadImage)

router.route('/:id')
        .patch(tokenMiddleware,allowTo('admin'),uploadImageMiddleware,articlesController.updateArticle)
        .delete(tokenMiddleware,allowTo('admin'),articlesController.deleteArticle)   
router.route('/:article_url')
        .get(articlesController.getArticleByUrl)
router.route('/category/:category_name')
        .get(articlesController.getArticlesByCategory)
router.route('/tag/:tag')
        .get(articlesController.getArticlesByTag)

module.exports=router