const mongoose = require('mongoose');

const propertySchema = new mongoose.Schema({
    name_ad_ar: { type: String, default: null },
    type: { type: String, enum: ['sale', 'rent'], default: null },
    rent_type: { type: String, default: null },
    discount: { type: Number, default: null },
    category: { type: String, default: null },
    sub_category: { type: String, default: null },
    user_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Users', default: null },
    governorate: { type: String, default: null },
    city: { type: String, default: null },
    region: { type: String, default: null },
    street: { type: String, default: null },
    full_address: { type: String, default: null },
    details_ar: { type: String, default: null },
    video_link: { type: String, default: null },
    view: { type: String, default: null },
    price: { type: Number, default: null },
    area: { type: Number, default: null },
    payment_method: { type: String, default: null },
    rooms: { type: Number, default: null },
    bathrooms: { type: Number, default: null },
    finishing_type: { type: String, default: null },
    floors: { type: Number, default: null },
    furnished: { type: String},
    department: { type: String, enum: ['commercial', 'administrative', 'medical'], default: null },
    status: { type: String, enum: ['جاهز', 'تحت الانشاء'], default: null },
    compound_name: { type: String, default: null },
    latitude: { type: Number, default: null },
    longitude: { type: Number, default: null },
    primary_picture: { type: String, default: null },
    images: { type: [], default: [] },
    floor_numooer: { type: Number, default: null },
    legal_papers: { type: String, default: null },
    deliver_date: { type: String, default: null },
    facilities: { type: [], default: [] },
    features: { type: [], default: [] },
    services: { type: [], default: [] },
    devices: { type: [], default: [] },
    accessories: { type: [], default: [] },
    price_per: { type: String, default: null },
    mall_name: { type: String, default: null },
    created_at: { type: Date, default: Date.now },
    updated_at: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Properties', propertySchema);
